#!/bin/bash
echo ""
echo""
clear
echo""
echo -e "\e[1;96m===================================================== > > >\e[m "
echo " "
printf "\e[1;31m[\e[0m\e[1;92m01\e[0m\e[1;31m] \e[0m\e[1;37;44m Termux \e[0m  "  
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"     
echo
printf "\e[1;31m[\e[0m\e[1;92m02\e[0m\e[1;31m] \e[0m\e[1;37;41m Linux \e[0m   "  
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"
echo " "
echo -e "\e[1;96m===================================================== > > >\e[m "
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m You Want to Choose System : \e[1;91m (1/2)  : \e[0m' option
echo""
echo""
echo""
if [[ $option == *'1'* ]]; then
echo""
cd /data/data/com.termux/files/usr/bin
./ngrok http 4444


fi
if [[ $option == *'2'* ]]; then
echo""
cd /usr/bin
./ngrok http 4444

fi





echo
