#!/bin/sh/hack-cctv-publik
# by mr virus spm
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# warna teks
blue='\033[34;1m'
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
green='\033[32;1m'
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
purple='\033[35;1m'
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
cyan='\033[36;1m'
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
red='\033[31;1m'
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
white='\033[37;1m'
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
yellow='\033[33;1m'
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
clear
xdg-open https://youtube.com/channel/UCSJohuQCtqfD2P73Z65g8jg
echo $green
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
# https://codingan/by/mr-virus-spm.index.html/bused-slebew
sleep 1
figlet CCHEK
echo
echo $cyan"      (+)"$yellow"  BY MR VIRUS SPM"$cyan"  (+)"
echo $green"☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪"    
echo $red"#"$yellow" MAFIA TEKNOLOGI INDONESIA"
echo $red"#"$yellow" MAFIA BUKANLAH HACKER"
echo $red"#"$yellow" MAFIA TETAPLAH MAFIA"
echo $green"☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪☪"
    sleep 1
    echo
    echo $green"["$cyan"1"$green"]"$red" MULAI"
    echo $green"["$cyan"2"$green"]"$red" KELUAR"
    echo $white
    sleep 1
read -p "=> " gruty
if [ $gruty = 1 ]; then
sleep 1
  git clone https://github.com/MrVirusSpm-07/mobile
  sleep 2
  echo $purple"Berhasil Menginstall github"$white
  sleep 2
  echo
  echo $purple"Berhasil Menginstall cd"$white
  cd mobile
  sleep 2
clear
echo $blue
sleep 1
figlet CCHEK
echo
echo $green"======================================"
echo $red"("$white"+"$red")"$white" Author : Mr Virus Spm"$red"          ("$white"+"$red")"
echo $red"("$white"+"$red")"$white" Team   : Mafia Teknologi"$red"       ("$white"+"$red")"
echo $red"("$white"+"$red")"$white" Script : Hack Cctv Publik"$red"      ("$white"+"$red")"
echo $green"======================================"
echo $cyan
sleep 2
  sh https_mrvirus_mobile.sh
fi
if [ $gruty = 2 ]; then
exit
fi
